name: "프론트엔드 이슈"
description: 프론트엔드 작업용 Issue 작성 기본 양식입니다.
labels: ["🛠 FE"]
title: "[fe] "
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[feat] 버튼 컴포넌트 만들기"
  - type: textarea
    id: feature-description
    attributes:
      label: 작업 설명
      description: 어떠한 기능을 추가하시는 건지 적어주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: 접근 방법
      description: 고려하신 방법이나, 접근에 대해서 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
